<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.0</Version>
    <LauncherGitHubUsername>sdemat</LauncherGitHubUsername>
    <LauncherProjectName>MinecraftModLauncher</LauncherProjectName>
    <LauncherContactUrl>https://github.com/adittrp/MinecraftModLauncher</LauncherContactUrl>
  </PropertyGroup>
  
  <ItemGroup>
    <AssemblyMetadata Include="GitHubUsername" Value="$(LauncherGitHubUsername)" />
    <AssemblyMetadata Include="ProjectName" Value="$(LauncherProjectName)" />
    <AssemblyMetadata Include="ContactUrl" Value="$(LauncherContactUrl)" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.8.0" />
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
</Project>
